# Generated by Django 5.2.11 on 2026-04-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='unique_client_email_phone',
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Телефон'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), ('phone__isnull', False)), fields=('email', 'phone'), name='unique_client_email_phone', violation_error_message='Клиент с таким email и телефоном уже существует.'),
        ),
    ]
